# Churn Modelling using Artificial Neural Network

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

 Importing the dataset

In [33]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


Label Encoding the "Gender" column

In [9]:
print(y)

[1 0 1 ... 1 1 0]


Encoding categorical data

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [15]:
X_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

### Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN model

 Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

 Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Training the ANN model

 Compiling the ANN

In [0]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

 Training the ANN on the Training set

In [46]:
ann.fit(X_train,y_train, batch_size=32,epochs=20)

Epoch 1/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8648
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8650
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8659
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8666
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8652
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3297 - accuracy: 0.8646
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8651
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3299 - accuracy: 0.8635
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8660
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8655

## Making the predictions and evaluating the model

### Predicting the Test set results

In [47]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)




[[1509   86]
 [ 193  212]]


 ### Model Accuracy

In [49]:
accuracy_score(y_test, y_pred)

0.8605